name: Release Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
  schedule:
  - cron: '*/5 * * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3.1.0
    - 
      name: Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images:
          ghcr.io/trickbooter/alpine-hello
        flavor: |
          latest=false
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GHCR
      if: github.event_name == 'release'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name == 'release' }}
        tags: ${{ steps.meta.outputs.tags }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name == 'schedule' }}
        tags: trickbooter/alpine-hello:latest
    - 
      name: Print GitHub event action
      run: |
        echo "${{ github.event.action }}"
        echo "${{ github.repository }}"
        echo "abc-${{ github.repository }}"